// Aero Engine — the cooked texture container v1: the frozen DFD tables, the labels and (from step 2)
// the hostile-input parser (task 3.3.2). See cooked_texture.hpp for the contract and
// docs/09-file-formats.md section 10 for the normative format. NEVER THROWS. NEVER READS A FILE.
// NEVER LOGS. NO FLOATING POINT.
#include <aero/assets/cooked_texture.hpp>

#include <array>
#include <cstddef>
#include <cstdint>
#include <span>
#include <string_view>

namespace engine::assets {
namespace {

// ---- the header's field offsets, named ONCE ------------------------------------------------------
// docs/09 section 10.2 is the normative table; these mirror it and nothing else in this TU spells a
// header offset as a literal. The chained static_asserts below are not decoration: they are what
// makes every one of these constants used, and they state the layout as arithmetic rather than as a
// comment somebody can contradict.
constexpr std::size_t H_IDENTIFIER = 0;
constexpr std::size_t H_VK_FORMAT = 12;
constexpr std::size_t H_TYPE_SIZE = 16;
constexpr std::size_t H_PIXEL_WIDTH = 20;
constexpr std::size_t H_PIXEL_HEIGHT = 24;
constexpr std::size_t H_PIXEL_DEPTH = 28;
constexpr std::size_t H_LAYER_COUNT = 32;
constexpr std::size_t H_FACE_COUNT = 36;
constexpr std::size_t H_LEVEL_COUNT = 40;
constexpr std::size_t H_SUPERCOMPRESSION = 44;
constexpr std::size_t H_DFD_OFFSET = 48;
constexpr std::size_t H_DFD_LENGTH = 52;
constexpr std::size_t H_KVD_OFFSET = 56;
constexpr std::size_t H_KVD_LENGTH = 60;
constexpr std::size_t H_SGD_OFFSET = 64;  // u64
constexpr std::size_t H_SGD_LENGTH = 72;  // u64
static_assert(H_IDENTIFIER == 0 && H_VK_FORMAT == KTX2_IDENTIFIER.size());
static_assert(H_TYPE_SIZE == H_VK_FORMAT + 4 && H_PIXEL_WIDTH == H_TYPE_SIZE + 4);
static_assert(H_PIXEL_HEIGHT == H_PIXEL_WIDTH + 4 && H_PIXEL_DEPTH == H_PIXEL_HEIGHT + 4);
static_assert(H_LAYER_COUNT == H_PIXEL_DEPTH + 4 && H_FACE_COUNT == H_LAYER_COUNT + 4);
static_assert(H_LEVEL_COUNT == H_FACE_COUNT + 4 && H_SUPERCOMPRESSION == H_LEVEL_COUNT + 4);
static_assert(H_DFD_OFFSET == H_SUPERCOMPRESSION + 4 && H_DFD_LENGTH == H_DFD_OFFSET + 4);
static_assert(H_KVD_OFFSET == H_DFD_LENGTH + 4 && H_KVD_LENGTH == H_KVD_OFFSET + 4);
static_assert(H_SGD_OFFSET == H_KVD_LENGTH + 4 && H_SGD_LENGTH == H_SGD_OFFSET + 8);
static_assert(H_SGD_LENGTH + 8 == KTX2_HEADER_BYTES);

// Level-record field offsets, relative to the record's own start.
constexpr std::size_t L_BYTE_OFFSET = 0;
constexpr std::size_t L_BYTE_LENGTH = 8;
constexpr std::size_t L_UNCOMPRESSED_LENGTH = 16;
static_assert(L_BYTE_OFFSET == 0 && L_BYTE_LENGTH == L_BYTE_OFFSET + 8);
static_assert(L_UNCOMPRESSED_LENGTH == L_BYTE_LENGTH + 8);
static_assert(L_UNCOMPRESSED_LENGTH + 8 == KTX2_LEVEL_RECORD_BYTES);

// ---- the eight frozen Data Format Descriptors ----------------------------------------------------
//
// DERIVED FROM dfdutils' OWN createdfd.c (createDFDCompressed / createDFDUnpacked / writeHeader /
// writeSample) AND khr_df.h, NOT BY HAND -- and then regenerated by compiling that file and dumping
// its output byte for byte, because our own parser compares the DFD against the same table our
// writer emits, so every test in this tree passes with a wrong table and only an external validator
// can tell. Layout of each: 4 bytes of dfdTotalSize, then six basic-block words, then 16 bytes per
// sample.
//   word 0  vendorId(0) | descriptorType(0) << 17
//   word 1  versionNumber(2) | descriptorBlockSize << 16   -- 2 is KHR_DF_VERSIONNUMBER_1_4, which
//                                                             khr_df.h notes did not bump the block
//                                                             version number from 1.3
//   word 2  colorModel | primaries(1, BT709) << 8 | transferFunction << 16 | flags(0, straight) << 24
//   word 3  (blockW-1) | (blockH-1) << 8 | (blockD-1) << 16 | (blockE-1) << 24   -- all zero unpacked
//   word 4  bytesPlane0 (the block byte size) in the low byte, planes 1..3 above it
//   word 5  bytesPlane4..7, all zero
//   sample  bitOffset | (bitLength-1) << 16 | channelId << 24 ; samplePosition ; lower ; upper
//
// THE ALPHA QUALIFIER, AND WHY THE sRGB TABLES ARE NOT ONE-BYTE EDITS OF THEIR UNORM SIBLINGS.
// setChannelFlags(channel, s_SRGB) sets KHR_DF_SAMPLE_DATATYPE_LINEAR (0x10) when the channel id
// equals KHR_DF_CHANNEL_RGBSDA_ALPHA (15), and both KHR_DF_CHANNEL_BC3_ALPHA and the alpha channel
// writeSample maps a channel-3 request to are ALSO 15 -- so BC3_SRGB's first sample and
// R8G8B8A8_SRGB's fourth carry channel byte 1F, not 0F. The KTX2 spec makes this a MUST, not a
// preference: "If transferFunction is not KHR_DF_TRANSFER_LINEAR or KHR_DF_TRANSFER_UNSPECIFIED and
// an alpha channel exists, KHR_DF_SAMPLE_DATATYPE_LINEAR must be set in the qualifiers field of the
// alpha sample." BC1_RGB_SRGB is genuinely a one-byte edit, because its only sample is channel 0.
// Do not "simplify" the three sRGB tables into byte patches of their siblings -- one of them is, two
// of them are not, and the two that are not are the ones an external validator rejects.
//
// THEY ARE EXPLICIT BYTE LITERALS AND NEVER SHIFT-AND-OR EXPRESSIONS, for two reasons. A table that
// is COMPUTED can be computed wrongly in a way its own reader agrees with, which is the circularity
// above. And `(uint32_t)channel << 24` with channel 128..132 shifts into a sign bit if the value is
// ever handled as a signed type -- createdfd.c carries its own comment about that. A literal cannot.

// 131 VK_FORMAT_BC1_RGB_UNORM_BLOCK -- 44 bytes, one sample.
constexpr std::array<std::uint8_t, KTX2_DFD_BYTES_1_SAMPLE> DFD_BC1_RGB_UNORM = {
    0x2C, 0x00, 0x00, 0x00,  // dfdTotalSize 44
    0x00, 0x00, 0x00, 0x00,  // word 0  vendorId 0 | descriptorType 0
    0x02, 0x00, 0x28, 0x00,  // word 1  versionNumber 2 | descriptorBlockSize 40
    0x80, 0x01, 0x01, 0x00,  // word 2  model 128 BC1A | primaries 1 | transfer 1 LINEAR | flags 0
    0x03, 0x03, 0x00, 0x00,  // word 3  texel block 4x4x1x1, each extent stored minus one
    0x08, 0x00, 0x00, 0x00,  // word 4  bytesPlane0 8
    0x00, 0x00, 0x00, 0x00,  // word 5  bytesPlane4..7 0
    0x00, 0x00, 0x3F, 0x00,  // sample 0  bitOffset 0 | bitLength 64 | channel 0 BC1A_COLOR
    0x00, 0x00, 0x00, 0x00,  //           samplePosition 0
    0x00, 0x00, 0x00, 0x00,  //           sampleLower 0
    0xFF, 0xFF, 0xFF, 0xFF,  //           sampleUpper 0xFFFFFFFF
};

// 132 VK_FORMAT_BC1_RGB_SRGB_BLOCK -- 131 with byte 14 only: transferFunction 1 -> 2. GENUINELY a
// one-byte edit, because BC1's single sample is channel 0 and the alpha rule above cannot reach it.
constexpr std::array<std::uint8_t, KTX2_DFD_BYTES_1_SAMPLE> DFD_BC1_RGB_SRGB = {
    0x2C, 0x00, 0x00, 0x00,  // dfdTotalSize 44
    0x00, 0x00, 0x00, 0x00,  // word 0  vendorId 0 | descriptorType 0
    0x02, 0x00, 0x28, 0x00,  // word 1  versionNumber 2 | descriptorBlockSize 40
    0x80, 0x01, 0x02, 0x00,  // word 2  model 128 BC1A | primaries 1 | transfer 2 SRGB | flags 0
    0x03, 0x03, 0x00, 0x00,  // word 3  texel block 4x4x1x1
    0x08, 0x00, 0x00, 0x00,  // word 4  bytesPlane0 8
    0x00, 0x00, 0x00, 0x00,  // word 5  bytesPlane4..7 0
    0x00, 0x00, 0x3F, 0x00,  // sample 0  bitOffset 0 | bitLength 64 | channel 0 BC1A_COLOR
    0x00, 0x00, 0x00, 0x00,  //           samplePosition 0
    0x00, 0x00, 0x00, 0x00,  //           sampleLower 0
    0xFF, 0xFF, 0xFF, 0xFF,  //           sampleUpper 0xFFFFFFFF
};

// 137 VK_FORMAT_BC3_UNORM_BLOCK -- 60 bytes, two samples: alpha first, then colour.
constexpr std::array<std::uint8_t, KTX2_DFD_BYTES_2_SAMPLE> DFD_BC3_UNORM = {
    0x3C, 0x00, 0x00, 0x00,  // dfdTotalSize 60
    0x00, 0x00, 0x00, 0x00,  // word 0  vendorId 0 | descriptorType 0
    0x02, 0x00, 0x38, 0x00,  // word 1  versionNumber 2 | descriptorBlockSize 56
    0x82, 0x01, 0x01, 0x00,  // word 2  model 130 BC3 | primaries 1 | transfer 1 LINEAR | flags 0
    0x03, 0x03, 0x00, 0x00,  // word 3  texel block 4x4x1x1
    0x10, 0x00, 0x00, 0x00,  // word 4  bytesPlane0 16
    0x00, 0x00, 0x00, 0x00,  // word 5  bytesPlane4..7 0
    0x00, 0x00, 0x3F, 0x0F,  // sample 0  bitOffset 0 | bitLength 64 | channel 15 BC3_ALPHA
    0x00, 0x00, 0x00, 0x00,  //           samplePosition 0
    0x00, 0x00, 0x00, 0x00,  //           sampleLower 0
    0xFF, 0xFF, 0xFF, 0xFF,  //           sampleUpper 0xFFFFFFFF
    0x40, 0x00, 0x3F, 0x00,  // sample 1  bitOffset 64 | bitLength 64 | channel 0 BC3_COLOR
    0x00, 0x00, 0x00, 0x00,  //           samplePosition 0
    0x00, 0x00, 0x00, 0x00,  //           sampleLower 0
    0xFF, 0xFF, 0xFF, 0xFF,  //           sampleUpper 0xFFFFFFFF
};

// 138 VK_FORMAT_BC3_SRGB_BLOCK -- 137 with TWO bytes changed, not one: byte 14 (transferFunction
// 1 -> 2) AND byte 31 (the alpha sample's channel id 0F -> 1F, the qualifier the spec makes a MUST).
constexpr std::array<std::uint8_t, KTX2_DFD_BYTES_2_SAMPLE> DFD_BC3_SRGB = {
    0x3C, 0x00, 0x00, 0x00,  // dfdTotalSize 60
    0x00, 0x00, 0x00, 0x00,  // word 0  vendorId 0 | descriptorType 0
    0x02, 0x00, 0x38, 0x00,  // word 1  versionNumber 2 | descriptorBlockSize 56
    0x82, 0x01, 0x02, 0x00,  // word 2  model 130 BC3 | primaries 1 | transfer 2 SRGB | flags 0
    0x03, 0x03, 0x00, 0x00,  // word 3  texel block 4x4x1x1
    0x10, 0x00, 0x00, 0x00,  // word 4  bytesPlane0 16
    0x00, 0x00, 0x00, 0x00,  // word 5  bytesPlane4..7 0
    0x00, 0x00, 0x3F, 0x1F,  // sample 0  channel 15 BC3_ALPHA | DATATYPE_LINEAR 0x10  <-- byte 31
    0x00, 0x00, 0x00, 0x00,  //           samplePosition 0
    0x00, 0x00, 0x00, 0x00,  //           sampleLower 0
    0xFF, 0xFF, 0xFF, 0xFF,  //           sampleUpper 0xFFFFFFFF
    0x40, 0x00, 0x3F, 0x00,  // sample 1  bitOffset 64 | bitLength 64 | channel 0 BC3_COLOR
    0x00, 0x00, 0x00, 0x00,  //           samplePosition 0
    0x00, 0x00, 0x00, 0x00,  //           sampleLower 0
    0xFF, 0xFF, 0xFF, 0xFF,  //           sampleUpper 0xFFFFFFFF
};

// 139 VK_FORMAT_BC4_UNORM_BLOCK -- 44 bytes. No sRGB sibling exists at any Vulkan value.
constexpr std::array<std::uint8_t, KTX2_DFD_BYTES_1_SAMPLE> DFD_BC4_UNORM = {
    0x2C, 0x00, 0x00, 0x00,  // dfdTotalSize 44
    0x00, 0x00, 0x00, 0x00,  // word 0  vendorId 0 | descriptorType 0
    0x02, 0x00, 0x28, 0x00,  // word 1  versionNumber 2 | descriptorBlockSize 40
    0x83, 0x01, 0x01, 0x00,  // word 2  model 131 BC4 | primaries 1 | transfer 1 LINEAR | flags 0
    0x03, 0x03, 0x00, 0x00,  // word 3  texel block 4x4x1x1
    0x08, 0x00, 0x00, 0x00,  // word 4  bytesPlane0 8
    0x00, 0x00, 0x00, 0x00,  // word 5  bytesPlane4..7 0
    0x00, 0x00, 0x3F, 0x00,  // sample 0  bitOffset 0 | bitLength 64 | channel 0 BC4_DATA
    0x00, 0x00, 0x00, 0x00,  //           samplePosition 0
    0x00, 0x00, 0x00, 0x00,  //           sampleLower 0
    0xFF, 0xFF, 0xFF, 0xFF,  //           sampleUpper 0xFFFFFFFF
};

// 141 VK_FORMAT_BC5_UNORM_BLOCK -- 60 bytes, two samples: red first, then green. No sRGB sibling.
constexpr std::array<std::uint8_t, KTX2_DFD_BYTES_2_SAMPLE> DFD_BC5_UNORM = {
    0x3C, 0x00, 0x00, 0x00,  // dfdTotalSize 60
    0x00, 0x00, 0x00, 0x00,  // word 0  vendorId 0 | descriptorType 0
    0x02, 0x00, 0x38, 0x00,  // word 1  versionNumber 2 | descriptorBlockSize 56
    0x84, 0x01, 0x01, 0x00,  // word 2  model 132 BC5 | primaries 1 | transfer 1 LINEAR | flags 0
    0x03, 0x03, 0x00, 0x00,  // word 3  texel block 4x4x1x1
    0x10, 0x00, 0x00, 0x00,  // word 4  bytesPlane0 16
    0x00, 0x00, 0x00, 0x00,  // word 5  bytesPlane4..7 0
    0x00, 0x00, 0x3F, 0x00,  // sample 0  bitOffset 0 | bitLength 64 | channel 0 BC5_RED
    0x00, 0x00, 0x00, 0x00,  //           samplePosition 0
    0x00, 0x00, 0x00, 0x00,  //           sampleLower 0
    0xFF, 0xFF, 0xFF, 0xFF,  //           sampleUpper 0xFFFFFFFF
    0x40, 0x00, 0x3F, 0x01,  // sample 1  bitOffset 64 | bitLength 64 | channel 1 BC5_GREEN
    0x00, 0x00, 0x00, 0x00,  //           samplePosition 0
    0x00, 0x00, 0x00, 0x00,  //           sampleLower 0
    0xFF, 0xFF, 0xFF, 0xFF,  //           sampleUpper 0xFFFFFFFF
};

// 37 VK_FORMAT_R8G8B8A8_UNORM -- 92 bytes, four samples, one per channel.
constexpr std::array<std::uint8_t, KTX2_DFD_BYTES_4_SAMPLE> DFD_RGBA8_UNORM = {
    0x5C, 0x00, 0x00, 0x00,  // dfdTotalSize 92
    0x00, 0x00, 0x00, 0x00,  // word 0  vendorId 0 | descriptorType 0
    0x02, 0x00, 0x58, 0x00,  // word 1  versionNumber 2 | descriptorBlockSize 88
    0x01, 0x01, 0x01, 0x00,  // word 2  model 1 RGBSDA | primaries 1 | transfer 1 LINEAR | flags 0
    0x00, 0x00, 0x00, 0x00,  // word 3  texel block 1x1x1x1 -- unpacked, so every extent is zero
    0x04, 0x00, 0x00, 0x00,  // word 4  bytesPlane0 4
    0x00, 0x00, 0x00, 0x00,  // word 5  bytesPlane4..7 0
    0x00, 0x00, 0x07, 0x00,  // sample 0  bitOffset 0 | bitLength 8 | channel 0 RED
    0x00, 0x00, 0x00, 0x00,  //           samplePosition 0
    0x00, 0x00, 0x00, 0x00,  //           sampleLower 0
    0xFF, 0x00, 0x00, 0x00,  //           sampleUpper 255
    0x08, 0x00, 0x07, 0x01,  // sample 1  bitOffset 8 | bitLength 8 | channel 1 GREEN
    0x00, 0x00, 0x00, 0x00,  //           samplePosition 0
    0x00, 0x00, 0x00, 0x00,  //           sampleLower 0
    0xFF, 0x00, 0x00, 0x00,  //           sampleUpper 255
    0x10, 0x00, 0x07, 0x02,  // sample 2  bitOffset 16 | bitLength 8 | channel 2 BLUE
    0x00, 0x00, 0x00, 0x00,  //           samplePosition 0
    0x00, 0x00, 0x00, 0x00,  //           sampleLower 0
    0xFF, 0x00, 0x00, 0x00,  //           sampleUpper 255
    0x18, 0x00, 0x07, 0x0F,  // sample 3  bitOffset 24 | bitLength 8 | channel 15 ALPHA
    0x00, 0x00, 0x00, 0x00,  //           samplePosition 0
    0x00, 0x00, 0x00, 0x00,  //           sampleLower 0
    0xFF, 0x00, 0x00, 0x00,  //           sampleUpper 255
};

// 43 VK_FORMAT_R8G8B8A8_SRGB -- 37 with TWO bytes changed, not one: byte 14 (transferFunction
// 1 -> 2) AND byte 79 (sample 3's channel id 0F -> 1F). Sample 3 starts at 28 + 3*16 = 76, and the
// channel id is the fourth byte of a sample's first word.
constexpr std::array<std::uint8_t, KTX2_DFD_BYTES_4_SAMPLE> DFD_RGBA8_SRGB = {
    0x5C, 0x00, 0x00, 0x00,  // dfdTotalSize 92
    0x00, 0x00, 0x00, 0x00,  // word 0  vendorId 0 | descriptorType 0
    0x02, 0x00, 0x58, 0x00,  // word 1  versionNumber 2 | descriptorBlockSize 88
    0x01, 0x01, 0x02, 0x00,  // word 2  model 1 RGBSDA | primaries 1 | transfer 2 SRGB | flags 0
    0x00, 0x00, 0x00, 0x00,  // word 3  texel block 1x1x1x1
    0x04, 0x00, 0x00, 0x00,  // word 4  bytesPlane0 4
    0x00, 0x00, 0x00, 0x00,  // word 5  bytesPlane4..7 0
    0x00, 0x00, 0x07, 0x00,  // sample 0  bitOffset 0 | bitLength 8 | channel 0 RED
    0x00, 0x00, 0x00, 0x00,  //           samplePosition 0
    0x00, 0x00, 0x00, 0x00,  //           sampleLower 0
    0xFF, 0x00, 0x00, 0x00,  //           sampleUpper 255
    0x08, 0x00, 0x07, 0x01,  // sample 1  bitOffset 8 | bitLength 8 | channel 1 GREEN
    0x00, 0x00, 0x00, 0x00,  //           samplePosition 0
    0x00, 0x00, 0x00, 0x00,  //           sampleLower 0
    0xFF, 0x00, 0x00, 0x00,  //           sampleUpper 255
    0x10, 0x00, 0x07, 0x02,  // sample 2  bitOffset 16 | bitLength 8 | channel 2 BLUE
    0x00, 0x00, 0x00, 0x00,  //           samplePosition 0
    0x00, 0x00, 0x00, 0x00,  //           sampleLower 0
    0xFF, 0x00, 0x00, 0x00,  //           sampleUpper 255
    0x18, 0x00, 0x07, 0x1F,  // sample 3  channel 15 ALPHA | DATATYPE_LINEAR 0x10   <-- byte 79
    0x00, 0x00, 0x00, 0x00,  //           samplePosition 0
    0x00, 0x00, 0x00, 0x00,  //           sampleLower 0
    0xFF, 0x00, 0x00, 0x00,  //           sampleUpper 255
};

}  // namespace

std::string_view toString(CookedTextureFormat format) noexcept {
    switch (format) {
        case CookedTextureFormat::Rgba8Unorm:
            return "Rgba8Unorm";
        case CookedTextureFormat::Rgba8Srgb:
            return "Rgba8Srgb";
        case CookedTextureFormat::Bc1RgbUnorm:
            return "Bc1RgbUnorm";
        case CookedTextureFormat::Bc1RgbSrgb:
            return "Bc1RgbSrgb";
        case CookedTextureFormat::Bc3Unorm:
            return "Bc3Unorm";
        case CookedTextureFormat::Bc3Srgb:
            return "Bc3Srgb";
        case CookedTextureFormat::Bc4Unorm:
            return "Bc4Unorm";
        case CookedTextureFormat::Bc5Unorm:
            return "Bc5Unorm";
    }
    return "Unknown";  // unreachable; the switch has no default so a new enumerator is a -Wswitch error
}

std::span<const std::uint8_t> cookedTextureDescriptorBytes(CookedTextureFormat format) noexcept {
    switch (format) {
        case CookedTextureFormat::Rgba8Unorm:
            return DFD_RGBA8_UNORM;
        case CookedTextureFormat::Rgba8Srgb:
            return DFD_RGBA8_SRGB;
        case CookedTextureFormat::Bc1RgbUnorm:
            return DFD_BC1_RGB_UNORM;
        case CookedTextureFormat::Bc1RgbSrgb:
            return DFD_BC1_RGB_SRGB;
        case CookedTextureFormat::Bc3Unorm:
            return DFD_BC3_UNORM;
        case CookedTextureFormat::Bc3Srgb:
            return DFD_BC3_SRGB;
        case CookedTextureFormat::Bc4Unorm:
            return DFD_BC4_UNORM;
        case CookedTextureFormat::Bc5Unorm:
            return DFD_BC5_UNORM;
    }
    return {};  // unreachable; the switch has no default so a new enumerator is a -Wswitch error
}

std::string_view cookedTextureStatusLabel(CookedTextureStatus status) noexcept {
    switch (status) {
        case CookedTextureStatus::Ok:
            return "Ok";
        case CookedTextureStatus::TooSmall:
            return "Too small";
        case CookedTextureStatus::BadIdentifier:
            return "Bad identifier";
        case CookedTextureStatus::UnsupportedFormat:
            return "Unsupported format";
        case CookedTextureStatus::UnsupportedShape:
            return "Unsupported shape";
        case CookedTextureStatus::Supercompressed:
            return "Supercompressed";
        case CookedTextureStatus::CapExceeded:
            return "Cap exceeded";
        case CookedTextureStatus::BadTable:
            return "Bad table";
        case CookedTextureStatus::BadRange:
            return "Bad range";
        case CookedTextureStatus::BadDescriptor:
            return "Bad descriptor";
    }
    return "Unknown";  // unreachable; the switch has no default so a new enumerator is a -Wswitch error
}

}  // namespace engine::assets
