# cmake/embed_run.cmake -- task E.6.1: run by cmake/embed.cmake's custom command as `cmake -P`, once per file.
# Writes one C++ translation unit holding INPUT's bytes as an integer array plus one accessor:
#
#     std::span<const std::uint8_t> <NAMESPACE>::<ACCESSOR>() noexcept;
#
# The checks repeat embed.cmake's configure-time ones, so a file replaced after configure is still caught. The
# output is written to a temporary and copied over only when different, so an unchanged input never recompiles
# the TU.
cmake_minimum_required(VERSION 3.28)

foreach(variable IN ITEMS INPUT OUTPUT ACCESSOR HEADER NAMESPACE)
    if(NOT DEFINED ${variable} OR "${${variable}}" STREQUAL "")
        message(FATAL_ERROR "embed: ${variable} is required")
    endif()
endforeach()
if(NOT ACCESSOR MATCHES "^[a-z][A-Za-z0-9]*$")
    message(FATAL_ERROR "embed: '${ACCESSOR}' is not a camelCase accessor")
endif()
if(NOT EXISTS "${INPUT}")
    message(FATAL_ERROR "embed: input '${INPUT}' does not exist")
endif()
file(SIZE "${INPUT}" inputSize)
if(inputSize EQUAL 0)
    message(FATAL_ERROR "embed: input '${INPUT}' is empty")
endif()
file(READ "${INPUT}" magic LIMIT 4 HEX)
if(NOT magic STREQUAL "00010000")
    message(FATAL_ERROR "embed: input '${INPUT}' is not a TrueType font (first bytes '${magic}')")
endif()

# Lower-case hex pairs -> "0xNN," -> a line break after every sixteenth element. CMake's regex has no {n}, so
# the sixteen-element pattern is spelled out.
file(READ "${INPUT}" hex HEX)
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
set(element "0x[0-9a-f][0-9a-f],")
set(sixteen "")
foreach(i RANGE 1 16)
    string(APPEND sixteen "${element}")
endforeach()
string(REGEX REPLACE "(${sixteen})" "\\1\n" bytes "${bytes}")

file(TO_CMAKE_PATH "${HEADER}" headerPath)
file(TO_CMAKE_PATH "${INPUT}" inputPath)
set(content "// GENERATED by cmake/embed_run.cmake from ${inputPath} -- do not edit, do not commit.\n")
string(APPEND content "#include \"${headerPath}\"\n\n#include <cstdint>\n#include <span>\n\n")
string(APPEND content "namespace ${NAMESPACE} {\nnamespace {\nconst std::uint8_t DATA[] = {\n${bytes}\n};\n")
string(APPEND content "}  // namespace\n\n")
string(APPEND content "std::span<const std::uint8_t> ${ACCESSOR}() noexcept { return DATA; }\n\n")
string(APPEND content "}  // namespace ${NAMESPACE}\n")

file(WRITE "${OUTPUT}.tmp" "${content}")
file(COPY_FILE "${OUTPUT}.tmp" "${OUTPUT}" ONLY_IF_DIFFERENT)
file(REMOVE "${OUTPUT}.tmp")
